import type { BattleProfile } from "./types"

export const MOCK_PROFILES: Record<string, BattleProfile> = {
  torvalds: {
    login: "torvalds",
    name: "Linus Torvalds",
    avatarUrl: "/avatars/user-1.webp",
    profileUrl: "https://github.com/torvalds",
    bio: "Creator of Linux and Git",
    publicRepos: 18,
    followers: 196000,
    following: 3,
    accountAgeDays: 12000,
    activityScore: 96,
    powerScore: 98,
  },
  "dan-abramov": {
    login: "dan-abramov",
    name: "Dan Abramov",
    avatarUrl: "/avatars/user-2.webp",
    profileUrl: "https://github.com/dan-abramov",
    bio: "Co-author of Redux and React",
    publicRepos: 52,
    followers: 166000,
    following: 303,
    accountAgeDays: 6400,
    activityScore: 91,
    powerScore: 94,
  },
  yyx990803: {
    login: "yyx990803",
    name: "Evan You",
    avatarUrl: "/avatars/user-3.webp",
    profileUrl: "https://github.com/yyx990803",
    bio: "Creator of Vue.js",
    publicRepos: 142,
    followers: 315000,
    following: 245,
    accountAgeDays: 8200,
    activityScore: 94,
    powerScore: 96,
  },
  "rich-harris": {
    login: "rich-harris",
    name: "Rich Harris",
    avatarUrl: "/avatars/user-4.webp",
    profileUrl: "https://github.com/rich-harris",
    bio: "Creator of Svelte and Rollup",
    publicRepos: 93,
    followers: 92000,
    following: 526,
    accountAgeDays: 6300,
    activityScore: 88,
    powerScore: 90,
  },
  microsoft: {
    login: "microsoft",
    name: "Microsoft",
    avatarUrl: "/avatars/user-5.webp",
    profileUrl: "https://github.com/microsoft",
    bio: "Open source software and tools",
    publicRepos: 2050,
    followers: 230000,
    following: 0,
    accountAgeDays: 15000,
    activityScore: 97,
    powerScore: 99,
  },
  gaearon: {
    login: "gaearon",
    name: "Dan Abramov",
    avatarUrl: "/avatars/user-6.webp",
    profileUrl: "https://github.com/gaearon",
    bio: "React core team member",
    publicRepos: 105,
    followers: 185000,
    following: 230,
    accountAgeDays: 6200,
    activityScore: 89,
    powerScore: 92,
  },
}
